name: Build and Deploy BeautyHub Backend

on:
  push:
    branches:
      - main # Yoki sizning asosiy branch nomingiz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-beautyhub-jar
          path: target/api.beautyhub.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build # Build jobi tugashini kutadi
    environment: production # Agar GitHub Environments ishlatsangiz
    steps:
      - uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: api-beautyhub-jar
          path: target/ # JAR faylni target/ papkasiga yuklaydi

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/api.beautyhub:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/api.beautyhub:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3 # SSH ulanish uchun mashhur Action
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/api.beautyhub:latest
            docker stop yodimdasiz-backend || true
            docker rm yodimdasiz-backend || true
            docker run -d --name yodimdasiz-backend --restart unless-stopped -p 10010:8080 ghcr.io/${{ github.repository }}/api.beautyhub:latest