### attach upload
POST http://localhost:8080/api/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1NDAyNjkzMiwiZXhwIjoxNzU0MTEzMzMyfQ.u5sT8xvxUfM1PeShpGN7YMhpMhZ4x6_-kyRCkvFzn88

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="logo1.jpg"

< C:\Users\hojia\Pictures\logo1.jpg

### attach open
GET http://localhost:8080/api/attach/open_general/65c4a6a4-1d38-48ef-a049-bbf8da7b446d.jpg


### attach download
GET http://localhost:8080/api/attach/download/logo1.jpg




