### attach upload
POST http://localhost:8080/api/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization:  Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MjI1NDIzNywiZXhwIjoxNzUyNTk5ODM3fQ.WE2_BWYX6c5DhR82xJ4QlkHlurjXnYjpIpTgivVTqSBg88KrYAiKKmYXmoaQy-4ZoD-v8a7SWiom87uwUMGmNw

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="logo1.jpg"

< C:\Users\hojia\Pictures\logo1.jpg

### attach open
GET http://localhost:8080/api/attach/open_general/65c4a6a4-1d38-48ef-a049-bbf8da7b446d.jpg





