###
POST http://localhost:8080/api/auth/registration
Content-Type: application/json
Accept-Language: en

{
  "fullName": "Ali Aliyev",
  "phone": "+998999476970",
  "password": "12345678",
  "confirmPassword": "12345678"
}

###
POST http://localhost:8080/api/auth/registration/login
Content-Type: application/json

{
  "phone": "+998995092376",
  "password": "12345678"
}


###
GET http://localhost:8080/api/auth/registration/verification
Content-Type: application/json

{
  "phone": "+998999476970",
  "code": "60248"
}

###
POST http://localhost:8080/api/auth/registration/reset
Content-Type: application/json

{
  "phone": "+998995092376"
}

###
POST http://localhost:8080/api/auth/registration/reset-password/confirm
Content-Type: application/json

{
  "phone": "+998772653507",
  "password": "123456789",
  "confirmPassword": "123456789"
}


