###
POST http://localhost:8080/api/auth/registration
Content-Type: application/json
Accept-Language: en

{
  "fullName": "Ali Aliyev",
  "phone": "+998995521968",
  "password": "12345678",
  "confirmPassword": "12345678"
}

###
POST http://localhost:8080/api/auth/registration/login
Content-Type: application/json

{
  "phone": "+998995092376",
  "password": "12345678"
}

###
GET http://localhost:8080/api/auth/registration/verification
Content-Type: application/json

{
  "phone": "+998999476970",
  "code": "60248"
}

###
POST http://localhost:8080/api/auth/registration/reset
Content-Type: application/json

{
  "phone": "+998995092376"
}

###
POST http://localhost:8080/api/auth/registration/reset-password/confirm
Content-Type: application/json

{
  "phone": "+998772653507",
  "password": "123456789",
  "confirmPassword": "123456789"
}



###Api log-out
POST http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzQxNjk5OCwiZXhwIjoxNzUzNTAzMzk4fQ.XNC7BcZsY99brfOOldF0SPsUe7m7zN7ovnah_aITvE4

