POST http://localhost:8080/api/chat/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzQxNjk5OCwiZXhwIjoxNzUzNTAzMzk4fQ.XNC7BcZsY99brfOOldF0SPsUe7m7zN7ovnah_aITvE4

{
  "recipientId": 2,
  "content": "Mazgimisiz?"
}

###
GET http://localhost:8080/api/chat/history/2?page=1&size=20
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzQxNjk5OCwiZXhwIjoxNzUzNTAzMzk4fQ.XNC7BcZsY99brfOOldF0SPsUe7m7zN7ovnah_aITvE4

###
PUT http://localhost:8080/api/chat/mark-as-read/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzI5ODQ4OCwiZXhwIjoxNzUzMzg0ODg4fQ.j9fBoh4qpH8gD44CHQx0pmPCh3NqIqvUuiVJsyOPLCM
