### profile update photo
PUT http://localhost:8080/api/profile/update/photo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MjkwMjQwNSwiZXhwIjoxNzUzMjQ4MDA1fQ.0CqoPyApYE5_PKBJAKjS6X1SKotNKVh6FyAstenukDg
Accept-Language: uz

{
  "photoId": "15fc9050-a8a1-437e-8e20-9cc8ecf14632.jpg"
}

### profile update password
PUT http://localhost:8080/api/profile/update/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzQ0NDQwNCwiZXhwIjoxNzUzNTMwODA0fQ.YqjIGb4GuAilV685Pci-pjb5pXn8yPpOgqJWDKATI_Y

{
  "newPassword": "12345678",
  "confirmPassword": "12345678"
}

### Profile update
PUT http://localhost:8080/api/profile/update/phone
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4NzcyNjUzNTA3Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MjkzMTgyMywiZXhwIjoxNzUzMjc3NDIzfQ.o7u1qMSvBl_5DapekqP8tHUJAtyspwgX_ZMP_6kqbDU
Accept-Language: en

{
  "phone": "+998995092376"
}

### Profile update confirm
POST http://localhost:8080/api/profile/update/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4NzcyNjUzNTA3Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MjkzMTgyMywiZXhwIjoxNzUzMjc3NDIzfQ.o7u1qMSvBl_5DapekqP8tHUJAtyspwgX_ZMP_6kqbDU

{
  "code": "34838"
}

###
POST http://localhost:8080/api/profile/update/language/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzA5ODU2MCwiZXhwIjoxNzUzNDQ0MTYwfQ.ybeAefVMs760ypEcYUpbU90JEPxfHWQOPNeHwk07_jw

{
  "languageCode": "en"
}

###
GET http://localhost:8080/api/profile/all/detail
Accept-Language: uz
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzQ0NDQwNCwiZXhwIjoxNzUzNTMwODA0fQ.YqjIGb4GuAilV685Pci-pjb5pXn8yPpOgqJWDKATI_Y


