###
POST http://localhost:8080/api/roots/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1MzgwODMwMiwiZXhwIjoxNzUzODk0NzAyfQ.VOGB93yI0hAsi1RXetCas-jqtGwgeZwhsPkDYF5vfsE

{
  "name": "roomName",
  "width": 4,
  "height": 8,
  "description": "nice room"
}

### get roots detail
GET http://localhost:8080/api/roots/all/detail
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1MzgwODMwMiwiZXhwIjoxNzUzODk0NzAyfQ.VOGB93yI0hAsi1RXetCas-jqtGwgeZwhsPkDYF5vfsE


### getByRoots
GET http://localhost:8080/api/roots/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1MzgwODMwMiwiZXhwIjoxNzUzODk0NzAyfQ.VOGB93yI0hAsi1RXetCas-jqtGwgeZwhsPkDYF5vfsE


###
PUT http://localhost:8080/api/roots/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1MzgwODMwMiwiZXhwIjoxNzUzODk0NzAyfQ.VOGB93yI0hAsi1RXetCas-jqtGwgeZwhsPkDYF5vfsE

{
  "name": "roomName",
  "width": 4,
  "height": 8,
  "description": "nice room"
}

### delete roots
DELETE http://localhost:8080/api/roots/delete/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzQ2NTk0OSwiZXhwIjoxNzUzNTUyMzQ5fQ.Y9ELsdUSEkdB6wT0gJARKStEZAqIkgc8YeF_uy4BRn8



