###
POST http://localhost:8080/api/salons/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzUyNjk2MywiZXhwIjoxNzUzNjEzMzYzfQ.9-avr1eJhF-qD4ipEiBA0Ue-hYA3mNge0SXMvyVr5-I

{
  "name": "Salon name",
  "address": "Shayxontoxur",
  "latitude": 35.65,
  "longitude": 44.45,
  "description": "perfect salon"
}

### Salon update
PUT http://localhost:8080/api/salons/update/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzUyNjk2MywiZXhwIjoxNzUzNjEzMzYzfQ.9-avr1eJhF-qD4ipEiBA0Ue-hYA3mNge0SXMvyVr5-I

{
  "name": "Salon name",
  "address": "Shayxontoxur",
  "latitude": 35.65,
  "longitude": 44.45,
  "description": "perfect saloni"
}

### get ById
GET http://localhost:8080/api/salons/get/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzUyNjk2MywiZXhwIjoxNzUzNjEzMzYzfQ.9-avr1eJhF-qD4ipEiBA0Ue-hYA3mNge0SXMvyVr5-I


### getAll Salons
GET https://beautyhubuz-3d777984d358.herokuapp.com/api/salons/getAll
#GET http://localhost:8080/api/salons/getAll
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoxLCJpYXQiOjE3NTU1MzM4MDEsImV4cCI6MTc1NTYyMDIwMX0.ZTEz3h-wAf9lOjKe_NlARWyJLqTLWhKhQNpnrHqMjXc


###
GET https://beautyhubuz-3d777984d358.herokuapp.com/api/salons/get/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoxLCJpYXQiOjE3NTU1MzM4MDEsImV4cCI6MTc1NTYyMDIwMX0.ZTEz3h-wAf9lOjKe_NlARWyJLqTLWhKhQNpnrHqMjXc


###
GET http://localhost:8080/api/salons/nearby?
    latitude=41.28141&
    longitude=69.212668&
    radiusKm=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5OTg5OTUwOTIzNzYiLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoyMSwiaWF0IjoxNzU1Nzc2OTMzLCJleHAiOjE3NTU4NjMzMzN9.kutuAHF7Aj8DcJU-9T9oRlXuqXGIxyaf3ISLp4r6mE8

###
GET https://beautyhubuz-3d777984d358.herokuapp.com/api/salons/nearby?
    latitude=41.28141&
    longitude=69.212668&
    radiusKm=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoxLCJpYXQiOjE3NTU3NzYxMTEsImV4cCI6MTc1NTg2MjUxMX0.5jEvAhZRg_Oa5nuKirP8ktKH4sFrhKzrA_4pci_RqBY


### salon search
GET http://localhost:8080/api/salons/search?
    query=Tashkent&
    category=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5OTg5OTUwOTIzNzYiLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoyMSwiaWF0IjoxNzU1Nzc2OTMzLCJleHAiOjE3NTU4NjMzMzN9.kutuAHF7Aj8DcJU-9T9oRlXuqXGIxyaf3ISLp4r6mE8

### salon search
GET https://beautyhubuz-3d777984d358.herokuapp.com/api/salons/search?
    query=Tashkent&
    category=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoxLCJpYXQiOjE3NTU3ODUwMDEsImV4cCI6MTc1NTg3MTQwMX0.1aSvuroscKlnS-mp5XnbIUm9M4NZE5Q99D0dFDf9bts


###
GET http://localhost:8080/api/reviews/api/v1/reviews/top-salons/?
    page=1&
    size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1NDIxMjQ1NywiZXhwIjoxNzU0Mjk4ODU3fQ.P0A3NsChQFhD1bTkngfaC7hwvephAvlbtVpNz5DvO6E