###
POST http://localhost:8080/api/salons/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzUyNjk2MywiZXhwIjoxNzUzNjEzMzYzfQ.9-avr1eJhF-qD4ipEiBA0Ue-hYA3mNge0SXMvyVr5-I

{
  "name": "Salon name",
  "address": "Shayxontoxur",
  "latitude": 35.65,
  "longitude": 44.45,
  "description": "perfect salon"
}

### Salon update
PUT http://localhost:8080/api/salons/update/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzUyNjk2MywiZXhwIjoxNzUzNjEzMzYzfQ.9-avr1eJhF-qD4ipEiBA0Ue-hYA3mNge0SXMvyVr5-I

{
  "name": "Salon name",
  "address": "Shayxontoxur",
  "latitude": 35.65,
  "longitude": 44.45,
  "description": "perfect saloni"
}

### get ById
GET http://localhost:8080/api/salons/get/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzUyNjk2MywiZXhwIjoxNzUzNjEzMzYzfQ.9-avr1eJhF-qD4ipEiBA0Ue-hYA3mNge0SXMvyVr5-I


### getAll Salons
GET https://beautyhubuz-3d777984d358.herokuapp.com/api/salons/getAll
#GET http://localhost:8080/api/salons/getAll
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoxLCJpYXQiOjE3NTU1MzM4MDEsImV4cCI6MTc1NTYyMDIwMX0.ZTEz3h-wAf9lOjKe_NlARWyJLqTLWhKhQNpnrHqMjXc


###
GET http://localhost:8080/api/salons/nearby?
    latitude=35.65&
    longitude=44.45&
    radiusKm=5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzUyNjk2MywiZXhwIjoxNzUzNjEzMzYzfQ.9-avr1eJhF-qD4ipEiBA0Ue-hYA3mNge0SXMvyVr5-I


### salon search
GET http://localhost:8080/api/salons/search?
    query=Shayxontoxur&
    category=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1MzUyNjk2MywiZXhwIjoxNzUzNjEzMzYzfQ.9-avr1eJhF-qD4ipEiBA0Ue-hYA3mNge0SXMvyVr5-I


###
GET http://localhost:8080/api/reviews/api/v1/reviews/top-salons/?
    page=1&
    size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTk1MDkyMzc2Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1NDIxMjQ1NywiZXhwIjoxNzU0Mjk4ODU3fQ.P0A3NsChQFhD1bTkngfaC7hwvephAvlbtVpNz5DvO6E