
### services create api
POST http://localhost:8080/api/v1/services/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1Mzc4NDcwNSwiZXhwIjoxNzUzODcxMTA1fQ.fO23iF-xi5xAsOxd9kPPwiX3B2T47hZr8aL_moFCuzM

{
  "salonId": 1,
  "name": "Erkaklar sochi",
  "description": "Professional erkaklar sochi qirqish xizmati",
  "durationMinutes": 30,
  "price": 25.5
}