### services create
POST http://localhost:8080/api/v1/services/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1MzgwNjcwMSwiZXhwIjoxNzUzODkzMTAxfQ.z6yvulnx5BiUi6X71fWwhyqFyAiFetAme-iLywQScj8

{
  "salonId": 1,
  "name": "Haircut 1",
  "description": "Short haircut",
  "durationMinutes": 30,
  "price": 20.0
}

### get services byId
GET http://localhost:8080/api/v1/services/21
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1MzgwNjcwMSwiZXhwIjoxNzUzODkzMTAxfQ.z6yvulnx5BiUi6X71fWwhyqFyAiFetAme-iLywQScj8


### get Salon byId
GET http://localhost:8080/api/v1/services/salon/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1MzgwNjcwMSwiZXhwIjoxNzUzODkzMTAxfQ.z6yvulnx5BiUi6X71fWwhyqFyAiFetAme-iLywQScj8



### update service
PUT http://localhost:8080/api/v1/services/update/22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1MzgwNjcwMSwiZXhwIjoxNzUzODkzMTAxfQ.z6yvulnx5BiUi6X71fWwhyqFyAiFetAme-iLywQScj8

{
  "salonId": 1,
  "name": "Haircut 1",
  "description": "Short haircut",
  "durationMinutes": 30,
  "price": 20.0
}


### delete service
DELETE http://localhost:8080/api/v1/services/delete/22
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIrOTk4OTkyNDMxMDY4Iiwicm9sZXMiOiJST0xFX1VTRVIsUk9MRV9NQVNURVIsUk9MRV9TQUxPTl9NQU5BR0VSIiwiaWQiOiIxMCIsImlhdCI6MTc1MzgwNjcwMSwiZXhwIjoxNzUzODkzMTAxfQ.z6yvulnx5BiUi6X71fWwhyqFyAiFetAme-iLywQScj8
